logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error
  path: ./logs
  file: code-generator-web.log
server:
  port: 8888
  servlet:
    context-path: /code-generator
spring:
  application:
    name: code-generator-web
  profiles:
    active: dev
  thymeleaf:
    cache: false
    mode: text
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .java
