debug: true
spring:
  datasource:
    druid: #参考官方分析性数据库的配置，后续根据业务修改
      filters: stat #监视filter
      initial-size: 5
      keep-alive: true
      max-active: 20
      max-evictable-idle-time-millis: 900000
      max-wait: 60000
      min-evictable-idle-time-millis: 600000
      min-idle: 10
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 2000
      web-stat-filter: # filter 配置
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 123456
    password: 123jiayouA!
    url: jdbc:mysql://118.25.93.104:3306/code-generator?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  # map的形式 包名+等级
  level:
    org.gentten: debug
  path: ./log